"""
Django settings for ais_ebike_rental project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Load .env (development convenience)
env = environ.Env()
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='1xa3m_0xij=hrl71mww296skb-$%0&51dp8_tmku0s4g6tm69-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Local apps
    'core.apps.CoreConfig',
    'riders',
    'admin_dashboard',
]

MIDDLEWARE = [
    # 'whitenoise.middleware.WhiteNoiseMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DailyAvailabilitySyncMiddleware',
]

ROOT_URLCONF = 'ais_ebike_rental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unread_notification_count',
                'core.context_processors.availability_sync_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'ais_ebike_rental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'  # Use custom login page

if DEBUG:  # Local development
    # Print emails to console during development
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # Email Configuration (Production) - Using environment variables for security
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = env('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='AIS E-Bike Rental <noreply@example.com>')

# Default receiver for Contact Us submissions (can be overridden by env var)
CONTACT_RECEIVER_EMAIL = env('CONTACT_RECEIVER_EMAIL', default='')

# Admin email for notifications (can be overridden by env var)
ADMIN_EMAIL = env('ADMIN_EMAIL', default=CONTACT_RECEIVER_EMAIL or '')

# Django Sites Framework
SITE_ID = 1

# Payments: Razorpay configuration (set these in your environment for production)
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET', default='')

# AI Configuration: Gemini API (Google Generative AI)
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

# Production Email Configuration Enhancements
# Configure email for better reliability in production
EMAIL_TIMEOUT = 30  # Timeout for email sending operations
EMAIL_USE_LOCALTIME = True  # Use local timezone in email timestamps

# Additional SMTP settings for production reliability
if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    # Enhanced SMTP settings
    EMAIL_SSL_CERTFILE = env('EMAIL_SSL_CERTFILE', default=None)
    EMAIL_SSL_KEYFILE = env('EMAIL_SSL_KEYFILE', default=None)
    EMAIL_USE_LOCALTIME = True

    # Connection pooling for better performance
    DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='AIS E-Bike Rental <noreply@aisebikerental.com>')

# Email logging for production monitoring
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': 'logs/email_errors.log',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django.core.mail': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }

# Server Email for notifications (like booking confirmations, cancellations)
SERVER_EMAIL = env('SERVER_EMAIL', default='')
MANAGERS = [('Admin Team', CONTACT_RECEIVER_EMAIL)]

# Email rate limiting (can be configured for production)
# EMAIL_RATE_LIMIT = env('EMAIL_RATE_LIMIT', default=100)  # emails per hour
