# Generated by Django 4.2.16 on 2025-09-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_verified_provider_user_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
