# Generated by Django 4.2.16 on 2025-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_is_approved_review_updated_at_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebike',
            name='address',
            field=models.CharField(blank=True, help_text='Street address or location name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ebike',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebike',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ebike',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ebike',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebike',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
