# Generated by Django 4.2.16 on 2025-10-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ebike',
            field=models.ForeignKey(blank=True, help_text='Review for a specific e-bike (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.ebike'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.ebike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ebike')},
            },
        ),
    ]
