# Generated by Django 4.2.16 on 2025-11-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_favorites_and_review_ebike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebike',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ebike',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ebike',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ebike',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ebike',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ebike',
            name='zip_code',
        ),
    ]
