# Generated by Django 5.1.7 on 2025-11-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='18:00', help_text='Return time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='09:00', help_text='Pickup time'),
        ),
    ]
