# Generated by Django 5.1.7 on 2025-11-23 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer or person's name", max_length=100)),
                ('role', models.CharField(help_text="Customer's role or title (e.g., 'Regular Commuter')", max_length=100)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image (150x150px recommended)', null=True, upload_to='testimonials/')),
                ('message', models.TextField(help_text='Testimonial message/content')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_highlight_1', models.CharField(blank=True, help_text="First rating highlight (e.g., 'Power: 5/5')", max_length=50, null=True)),
                ('rating_highlight_2', models.CharField(blank=True, help_text="Second rating highlight (e.g., 'Battery: 5/5')", max_length=50, null=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Display as featured/highlighted testimonial')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the homepage')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Booking Created - Payment Pending'), ('awaiting_approval', 'Payment Successful - Awaiting Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
